baseurl = "/"
languageCode = "en-us"
theme = "hello_friend"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  description = "Homepage for Colorful records by Saynt"
  keywords = "homepage, Colorful records, Saynt, records, music, producer"
  images = [""]

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # Default theme "light" or "dark"
  defaultTheme = "dark"

  # Social icons
  [[params.social]]
    name = "instagram"
    url  = "https://www.instagram.com/sayntsphere/"

  [[params.social]]
    name = "youtube"
    url  = "https://www.youtube.com/channel/UC0-EoKJQDAp2QhyLJYnVr7w"

  [[params.social]]
    name = "soundcloud"
    url  = "https://soundcloud.com/sayntsphere"
  
  [[params.social]]
    name = "facebook"
    url  = "https://www.facebook.com/sayntsphere/"
  
  [[params.social]]
    name = "email"
    url  = "mailto:info@colorfulrecords.com"

[languages]
  [languages.en]
    title = "Colorful Records"
    subtitle = "Saynt"
    keywords = ""
    copyright = "Colorful Records Inc."
    readOtherPosts = "Read other posts"
    homeSubtitle = "I N C ."

    [languages.en.params.logo]
      logoText = "Colorful Records®"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

	# You can create a language based menu
    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "publications"
        name = "Publications"
        url = "/publications"
      [[languages.en.menu.main]]
        identifier = "contact"
        name = "Contact"
        url = "/contact"
      [[languages.en.menu.main]]
        identifier = "events"
        name = "Events"
        url = "/events"

# And you can even create generic menu
[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"
  [[menu.main]]
    identifier = "publications"
    name = "Publications"
    url = "/publications"  
  [[menu.main]]
    identifier = "events"
    name = "Events"
    url = "/events"
  [[menu.main]]
    identifier = "contact"
    name       = "Contact"
    url        = "/contact"